### ISSUE TITLE
Name Change Unbans

### ISSUE THREAD

**Issue by FourDown** [BanManagement/BanManager#142]
Hey,

Currently, when a user is banned and then changes their name, to unban them you must use their original name.

Is it possible to make it so that you can use either their old name, or their new name to unban them?

Thanks!

**Comment by confuser** [comment]
It won't be possible to do both without changing the database structure, which I'd rather not do at this stage for v5.

At the moment, their name is only updated in the database, when they successfully join the server.

Would it not be better to keep banned player names as their old name for references to reports etc?

**Comment by Kakifrucht** [comment]
Better keep the old ones. You banned their old name, you know their old name.

**Comment by FourDown** [comment]
"Would it not be better to keep banned player names as their old name for references to reports etc?"
Yes, I was hoping for the ability to unban them via either account name. 

"Better keep the old ones."
Please read my ticket. I clearly request the ability to keep both, not remove the old name.

"You banned their old name, you know their old name."
I run a network with a big staff team. I am not the person responsible for 99% of the bans on my network.

**Comment by Kakifrucht** [comment]
I see your point, however this would require another database change as he mentioned. If it is either the one or the other, I prefer keeping it.

**Comment by FourDown** [comment]
@confuser What would happen if another player changed their name to the original name, joined the server and did something resulting in them needing to be banned?

Would it say the person was already banned? Also, how would unbanning the original player work at that point?

**Comment by roastnewt** [comment]
Would it require a database change?  The db stores player UUIDs, can't you convert the new name to UUID  and retrieve the row using UUID?

**Comment by confuser** [comment]
@FourDown That's a good question, one which has just been asked by my staff.

Apologies in advance to those who are watching this issue or repo, this is a pretty long explanation.

So old names are available after 37 days of not being used by the person who originally had that name.

There are two ways to find out if a person has changed their name.

1) A lookup to mojang with their name to find out what their UUID is, or with their UUID to find all their names.
2) Wait for them to join and see if what is stored is different.

The first option is obviously out of the question, thanks to Mojosoft's rate limiting and inability to stick their hands in their pockets and actually spend money to scale their API to cope with the traffic; for name lookups at least anyway.

That leaves us only with the second option; waiting for them to join the server, which is what is currently implemented into BanManager, and what Dinnerbone advocated on Twitter when someone had this similar problem/question.

PersonA is banned, they change their name to PersonAX, but are still banned.
PersonB changes their name to PersonA, 37 days after the original PersonA changed their name.

The new PersonA has never joined the server, and PersonAX can't because they are banned.

/bminfo and other commands will still show the PersonAX as PersonA. To resolve this, BM should store player data, and update it, regardless of if they're banned or not. Currently it only updates if they're able to join the server i.e. not banned. So that will need changing to accommodate for this scenario.

However, lets take another scenario..

PersonAX is still banned, but hasn't attempted to join the server since they were banned, and are therefore still referenced as PersonA in the database. The new PersonA joins the server, their name is updated from PersonB to PersonA in the database against their UUID. We now have a problem, there are two PersonA's in the player data table.

/bminfo will now fail, as a lookup via a name causes this statement to fail, https://github.com/confuser/Ban-Management/blob/master/src/main/java/me/confuser/banmanager/storage/PlayerStorage.java#L100 as there is more than one result and it doesn't make a mojang api lookup request.

/ban's and other commands will also have problems via the name, as there is more than one, it'll do a lookup to Mojang which may fail due to rate limiting. If it succeeds, the ban will be against the correct user, but the database will still have duplicate names.

So, to resolve this situation, when a player joins the server, BM needs to check to see if another player already exists with that name in it's database. If it does, make a request to check to see what their new name is, e.g. https://api.mojang.com/user/profiles/ae51c8493f2a4a37986d55ed5b02307f/names which as far as I can tell, is not rate limited, but there is always a possibility it might be in the future.

That then begs the question, should we explicitly rely on that request, how reliable is it, and how future proof will that API route be in terms of rate limiting, if not, what are the alternatives.

**Comment by confuser** [comment]
Unfortunately for networks which use separate tables for each server like we do at Frostcast, it'll be inevitable to end up with states like these, where some have the new name, but others don't, due to players not joining all the servers.

http://www.frostcast.net/bans/player/confuserr
http://www.frostcast.net/bans/player/confuser

**Comment by confuser** [comment]
Both scenarios should now be covered in build 51, however, not tested.
