### ISSUE TITLE
Bug with the sql/web-end

### ISSUE THREAD

**Issue by maxlehot1234** [BanManagement/BanManager#181]
Hi, I can't configure the MYSQL...

I try to accced this page: http://blocs-craft.com/bans/index.php?action=admin1

Hi see: Action not found, possible hacking attempt

I try to use the admin panel to add a server, I enter ALL GOOD informations, but I see this:
Error
Players table not found

So where I need MYSQL information needed before to add minecraft server??

**Comment by Orenthion** [comment]
Please make Tickets for issues with the Web-UI over at the [Ban Management Web-UI github](https://github.com/BanManagement/BanManager-WebUI/issues).

**Comment by Orenthion** [comment]
The reason this link: http://blocs-craft.com/bans/index.php?action=admin1 doesn't work is because the action is _admin_ not _admin1_

You should be able to reach the ACP from http://blocs-craft.com/bans/index.php?action=admin

Let us know a few things:
1. What web version are you using?
2. What plugin version are you using?
3. Is the website hosted locally, on a free site, or dedicated?

**Comment by maxlehot1234** [comment]
It is OK I found the problem... So you can close this ticket ;)

**Comment by Orenthion** [comment]
Ban Manager is not supported for Cracked Servers. The plugin requires the use of UUIDs and cracked accounts do not have this.

**Comment by frdmn** [comment]
What @Orenthion said
