### ISSUE TITLE
Enhancement: Improve /bminfo even more

### ISSUE THREAD

**Issue by EvilOlaf** [BanManagement/BanManager#244]
Good afternoon,

I was thinking about how to improve the `/bminfo` command even further so there is actually less need for the webinterface. I'm actually using the webinterface and I like it, but not every Minecraft server has the possibility, the needs or maybe the funds to pay a webserver too.

Currently `/bminfo` shows - depending on the permission setup - various information like the number of infractions (kicks, bans and such things), possible alts and so on.

My suggestion is to either add another permission node like `bm.command.bminfo.verbose` or an additional parameter for the `/bminfo` command like `/bminfo -v [player name]` (with the latest changes the player name is optional, thanks for that).

This would output some kind a table which lists all records of a player, sorted by warnings, kicks and so on, showing when, who and why. Pretty much like in the webinterface. If a player has a lot of records the output could get cut down with a reason "too many entries" or sort in multiple pages.

Another solution for this would be to add parameters like `-warns` or `-kicks` to selectively show entries sorted by type. This also could be split up in multiple permission nodes like `bm.command.bminfo.kicks` and so on but I don't think this is necessary.

Thanks for reading.

Best regards
Olaf

**Comment by confuser** [comment]
I'm not overly fond of -v, as like you say, the amount of data that could be spit out may be vast. Trying to handle that within minecraft chat which has somewhat little space will be quite difficult, perhaps impossible for some users with long histories.

I do quite like the idea of using command flags for the different records, which will be even easier to now implement since the addition of the silence feature.

How does this as an example sound?

`/bminfo [player] --kicks --warnings --muterecords --banrecords`
`/bminfo [player] -k -w -m -b`

For flexibility for all users, I think the different permission nodes will be a necessity.

I'm not sure whether to add --notes/-n as well, as `/notes` handles that, but it would be nice to have a uniform way of viewing all that data in game.

As for actual data output, have you got any suggestions as to it's look? The data could be output in chronological order, similar to `/bmactivity` rather than attempting to tabulate it by type.

Perhaps an optional `-time 12d` flag as well in order to restrict the results, to avoid having to see records that are perhaps far too outdated for one to care.

**Comment by EvilOlaf** [comment]
Hey @confuser 

I understand your point about `-v`, but it would be nice to have all information at one command...well `/bminfo` delivers this information in numbers though.

Why not `--mutes` and `--bans` instead of `--muterecords --banrecords`. 
I like the Linux-like syntax for long and short parameters.

A ´--notes -n` parameter could be added for the sake of completeness, even /notes does the same job. 

I think chronological output for an overview is a good choice, because you would be able to go into detail by using the `/bminfo` command with parameters.

The `-time` flag could be useful too. Some server administrators don't care how long the time since an infraction is, others say 'yes, infractions become time-barred'. So you can clearly say after X days there was no infraction of the rules.

**Comment by mcraftpete** [comment]
I really like this idea too  , I currently have 60+ staff and its hard to redirect them all to the website , I haven't even worked out how to make this work with enjin and don't even like the idea of accessing the sql from somewhere else (sql injection).
So the possibility to see a players ban history mute history and kicks history is awesome , I currently alredy have something similar to this from gesuit but its very very outdated and I am itching to change over to this plugin which uses spigot side rather then reliance on bungee.
To just show top 10 is great , to show page 1 of x is also cool , and yes I like the idea of the time.

**Comment by EvilOlaf** [comment]
Awesome
