### ISSUE TITLE
[player] doesnt work

### ISSUE THREAD

**Issue by XenRevo** [BanManagement/BanManager#290]
The [player] doesnt work in the messages for 
  sender:
    error:
      notFound: '&c[player] not found, are you sure they exist?'
      offline: '&c[player] is offline'
      noSelf: '&cYou cannot perform that action on yourself!'
etc......

**Comment by confuser** [comment]
Not all messages output [player] nor other variables.

If you can give me a list of any messages that you'd like to use those in, I'll ensure they're output correctly.

**Comment by XenRevo** [comment]
Could you add it for for when you do /ban or /mute <player> and the player is not online? So that [player] works.
Could you also add [expires] to the ban,player.disabllowed? So that this doesnt look bad 
https://i.revo.pw/2495hx1_2496Zx.png

**Comment by confuser** [comment]
`ban.player.disallowed` are permanent bans and so do not have an expiry time, simply use "never" or some other word instead of the expires token.

Not sure which messages you are referring to for /ban and /mute when they're not online. The notification messages correctly set the player token. Do you mean `sender.error.offlinePermission`?

**Comment by XenRevo** [comment]
Alright, I can use "Never" for that.

I mean ```sender.error.offline```

**Comment by Maescool** [comment]
I've gotten message [player] was banned for.. bla bla
with a player who connected with a new username (so namechanged)

**Comment by confuser** [comment]
Kick commands are the only ones that use sender.error.offline, which already sets [player] token
