### ISSUE TITLE
Feature Request - Store players in banmanager folder and other bans/warns/notes as backup

### ISSUE THREAD

**Issue by Legoman99573** [BanManagement/BanManager#364]
I feel this needs to be added for Owners with bad pinging to their database online, but this feature can be disableable. The reason i want this is because when i try to ban a player, they dont show up on the database, and i look and find an error message. plus can you also addin /ban inport usercache. This would help convert that into a place for players being logged, but doesnt expire. Pretty much uses usercache.json file in the server like importing bans from banned-players.json. Add a file named backups in the Banmanager folder will solve no player found issue.

**Comment by confuser** [comment]
This won't be added. BanManager makes primary use of a persisted hosted storage service, i.e. MySQL, and has done since its conception 3 years ago.

If you have problems with your database, find a more stable host if you wish to use this plugin.

What you're requesting is such a large feature/rewrite with little to no benefit.

**Comment by Legoman99573** [comment]
Could you add at least this command, /bm import players which will load players to the database from essentials, but keep it little essentials dependant, shouldnt require a recode. it can import them faster than waiting for all 150 of them to show up.
