### ISSUE TITLE
Optional reason argument for /unban command

### ISSUE THREAD

**Issue by Agazed** [BanManagement/BanManager#385]
Would be great for checking why a staff member unbanned someone.

Wrong name, appeal accepted, bought unban pass, mistake

Easy for keeping track why someone needed to be unbanned:

    /unban <player> [reason]

**Comment by EvilOlaf** [comment]
+1. Should be an optional argument though.

**Comment by confuser** [comment]
I'd like to add this to the record tables, but if it's optional, it seems like a redundant column. Only normalisation alternative would be to create a new table but that seems a little extreme.

Would be nice to have on Frostcast too. I'll see if I can get this done today :+1:

**Comment by EvilOlaf** [comment]
Uh yeah. 
Just scrolled through the commit and it seems like changes in `messages.yml` are missing.

**Comment by Agazed** [comment]
Wow! Didn't think this would get added let alone in a few hours.

Do I need to reset my database or anything? Anything I can configure?

Great work and thank you.

**Comment by confuser** [comment]
The developer build will automatically add the columns. I've tested it, and it's working nicely. Just take note that the reasons are only stored in the database and are not yet within /bminfo.

They need to be added to the web interface cc @frdmn 

I've left them out of the messages as they were odd without the reason due to joining words such as 'for'. Feel free to add [reason] to the unban notifications, the token will be replaced with the unban reason.

**Comment by Agazed** [comment]
Awesome. Do you have a CI server or do I have to compile myself?

**Comment by Agazed** [comment]
Nevermind, found your server.

**Comment by EvilOlaf** [comment]
As the reason is optional that would look weird when I add "for reason" and the reason is empty. In perfect condition there would be two messages. One handles with reason and one without. 
As workaround I could put the reason ta the end and add something like "if provided"... 
I'll see...

**Comment by Agazed** [comment]
Mines set up like this

    [player] has been unbanned by [actor] ([reason])

**Comment by Agazed** [comment]
Yes but I force my staff to type a reason.
