### ISSUE TITLE
Hooks Issue

### ISSUE THREAD

**Issue by TemptingMC** [BanManagement/BanManager#397]
Hey, I really need this done ASAP as my network releases is under a week and im expecting 500+ on it.

Anyways,
you added hooks for unbanip, I need the hook to be unban.
Example:
    unban:
      post:
      - cmd: unbanip [player]

Cause staff will be unbanning the player and then the ip will be unbanned.

**Comment by confuser** [comment]
You can already achieve this, the exact way in your example. The unban hook was added, the commit message is quite clear

> Added post hooks for unban, unbanip, unbaniprange, unmute

**Comment by frdmn** [comment]
Also, please keep in mind that this is an open source project where you cant expect any SLA response times nor implemention deadlines for feature requests or enterprise support.

We all have also real lives and sometimes more important stuff to do than maintaining a Minecraft plugin/project.

**Comment by EvilOlaf** [comment]
If you really need this you can also achieve this by using a 3rd party plugin like MyCommand and replace the `unban` command with a script that does both `unban` as well as `unbanip`.

**Comment by TemptingMC** [comment]
In the download msg it didn't say unban. Only ip things. Anyways, I tested
the plugin and the unban hook didn't work so I guess I should report that
here. I understand its a dev build.

**Comment by Kakifrucht** [comment]
Well, saying that you need stuff done asap on a free open source project is usually not the right way of approaching this. Most here don't really care if you have more players. You are not being prioritized like that.

**Comment by TemptingMC** [comment]
Fabian, how about you relax?

I didn't ask to be prioritized, but I'm asking for it to be done ASAP as I
love using this plugin.

Obviously your another one of those kids who trash forum threads/pull
requests, I'll go ahead and ignore you.

**Comment by confuser** [comment]
@TemptingMC the issue should be fixed in the latest developer build. 

As for your attitude, I really don't care what network you run, nor the amount of players. This project is developed for Frostcast, one of the oldest Minecraft communities; which I run in my spare time, and like others, I also work full time. 

As others have said, this is an open source project, things will get done when I or others (via pull requests) have spare time. Asking for something to be done ASAP is not going to complete it any quicker, and is in fact asking for it to be prioritised. Regardless, this is a moot point as the problem is fixed.
