### ISSUE TITLE
command not working on Bukkit 1.8.3

### ISSUE THREAD

**Issue by vanthoi** [BanManagement/BanManager#490]
Table bm_players on mysql have only Consoler not have player !
Command not working. Because a aler player not exit!
But player is Online!
I user OS Linux Centos 7 and Java 8
Please fix! Thanks!

**Comment by EvilOlaf** [comment]
Logs??

**Comment by vanthoi** [comment]
[15:45:09] [Server thread/INFO]: vanthoi issued server command: /bmban giaosu chanqua
[15:45:09] [Server thread/INFO]: [CommandEdit] Command Edit catched the following command: /bmban giaosu chanqua
[15:45:09] [pool-3-thread-150/INFO]: [BanManager] Requesting UUIDs for giaosu

**Comment by vanthoi** [comment]
http://img.ketnoidamme.vn/images/NPO5.png
http://img.ketnoidamme.vn/images/nmVBt.png

**Comment by vanthoi** [comment]
[15:57:52] [Server thread/INFO]: vanthoi issued server command: /tempmute giaosu 10m block
[15:57:52] [Server thread/INFO]: [CommandEdit] Command Edit catched the following command: /tempmute giaosu 10m block
[15:57:52] [pool-3-thread-173/INFO]: [BanManager] Requesting UUIDs for giaosu

**Comment by vanthoi** [comment]
I figured it was due to an error on linux distinguish ordinary characters and uppercase characters.
Therefore all accounts will not find it because the first character is uppercase self regulation. And if you apply for an account command does not exist, the work!
Please fix!
Thanks!

**Comment by Hu5ker** [comment]
I got the same issue. And is since two or 3 updates ago. Well, sice the plugin supports 1.8.X

If we try to kick some player, it says that the player doesn't exisist. But the player is in the server. Same problem with ban and banip.

Is not with all the players, just with some of them.

Other error that I saw is that with some players, if you ban them, they're still in the server. But the plugin says that the player was banned.

And the new one is if you type /ban - /kick /tempmute or /mute or nay other command from Ban Manager and then press Tab to get the name of the player in the chat, it doesn't work

For example: If I type /ban H and after the H I press Tab key to get the name Hu5ker, it dosen't work.

I have to type Hu5ker first in the chat, and then type the whole command.

**Comment by confuser** [comment]
Are you running in offline mode?

**Comment by Kixot14** [comment]
Confuser, if your plugin don't support offline mode, you should write about it with BIG RED LETTERS on top of the main page of plugin!
I lost 40+ hours in total, when configure your plugin and this intricate system of perms... And in the end  i find out that this plugin don't support offline mode without UUIDs...

**Comment by Kakifrucht** [comment]
Offline mode is not officially supported by anything, so if you want to find out if a plugin is supported, you should check that first, not the other way round.

**Comment by frdmn** [comment]
@Kixot14 While we potentially could add a huge warning in font size 70pt, it's actually your job to check the requirements of a specific piece of software that you plan to implement in your productive server infrastructure. Either that or try it out first in a test environment.
