### ISSUE TITLE
Chatcontrol chat compatibility

### ISSUE THREAD

**Issue by ziutekkk** [BanManagement/BanManager#546]
Hello
I use chatcontrol chat formatter. I wonder why banmanager mute doesn't work with that.
Im sure it works well with essentialschat and normal formatting but when I mute player, he can still write on chat.
Here is ss which proves that: http://scr.hu/0mdx/8ebo3
Is it any way to fix that?
Thanks

**Comment by confuser** [comment]
I'm not familiar with ChatControl. If it doesn't use the AsyncPlayerChatEvent to allow other plugins to check the message before it's sent, the plugin will need to add in checks directly with the BanManager API, via the BmAPI class

**Comment by EvilOlaf** [comment]
As I use BM with CHC as well I'll crosspost this into the proper repository to clarify this.
However I did not test this yet. I also did not get any negative feedback from team mates that this won't work.
Do you use CHC Pro or free?

**Comment by kangarko** [comment]
Hello,

I am unable to test BanManager (running on local mysql) build 48 on Spigot 1.9. It creates the database and table, but once the player is muted, they can continue to talk. ChatControl is not even installed on the server, only Vault, PermissionsEx and EssentialsX.

Other than that, I would say this is a priority issue. ChatControl listens to AsyncPlayerChatEvent and the priority is changeable in **Listener_Priority.Formatter **and **Listener_Priority.Checker **in settings.yml. I would recommend changing them to HIGH or LOW, to see if it helps, because ChatControl ignores cancelled events, so it must listen to the event _after _it is cancelled by BanManager.

**Comment by ziutekkk** [comment]
Ok I changed priority in chatcontrol pro to high and high.
Now players can't speak after mute, so it looks like it is fixed
Thanks for feedback

**Comment by EvilOlaf** [comment]
This should be added to documentation of either BM or CHC ;)

**Comment by kangarko** [comment]
There are plenty of plugins which require CHC's user to change the priority, so it is impossible to enumerate them all. There is already some general information on that listener_priority section, but I can add even more info.
