### ISSUE TITLE
BanManager Connection Leak Detection

### ISSUE THREAD

**Issue by SioWolf** [BanManagement/BanManager#576]
Every morning at 5AM EST BanManager throws a connection leak detection error and either A) Crashes the server or B) Spams the console with errors and causes everyone to time out.

http://pastebin.com/Dsu4wUhZ

**Comment by confuser** [comment]
It means you have a slowdown in your database. Are you running backups at 5am?

**Comment by SioWolf** [comment]
Yes, actually, I do a MySQLDump at 5am.

**Comment by confuser** [comment]
By default, `mysqldump` will lock tables, preventing reads and writes, hence your timeout problems. This is not an issue with BanManager. The exception simply made you aware of the problem.

**Comment by EvilOlaf** [comment]
Interesting. I also do dumps hourly but have no issues like this. Actually I am not sure if you are right, @confuser. As far as I read about that stuff is that you can do dumps while data is in use but these dumps may in some rare cases not be 100% functional. 

So beside those hourly backups I also make a full backup while the server is stopped. So I can safely so things like `flush tables with read lock;` to make a clean dump and later `unlock tables;` again.

**Comment by confuser** [comment]
@EvilOlaf There are different options when running the command in which this can be avoided; however by default this scenario is what occurs. 

Please also note that BM uses MySIAM tables for a reason, and switching to InnoDB (which you may have seen recommended in a lot of places) may cause issues when syncing.

This is more of a general sys admin issue rather than specific to BM.
