### ISSUE TITLE
Offline mode case insensitive UUID support

### ISSUE THREAD

**Issue by rautamiekka** [BanManagement/BanManager#582]
Follow up to #581.

**Comment by EvilOlaf** [comment]
This would probably be useful in offline mode only.
However BM does not support offline mode natively and will not officially, but feel free to work on this by yourself. Pull requests which improves the offline mode support will be accepted.

**Comment by confuser** [comment]
As stated in the original issue:

> The issue is with uuid generation on the Player object. It'd require a lot of refactoring. Happy to accept PRs.

Bukkit in offline mode considers players with different cases e.g. Confuser and confuser to be separate players, and generates a different UUID for each. Due to the extensive use of `getUniqueId` throughout the plugin, it'll be a large undertaking, one I'm not particularly interested in doing myself right now.

**Comment by rautamiekka** [comment]
That makes perfect sense. Would have to take it to Spigot first.

**Comment by Bodyash** [comment]
![default](https://cloud.githubusercontent.com/assets/2454569/14674580/7466a3a8-070d-11e6-820c-f7be830fdd23.PNG)
Ban one nick - ban the same with another case. Player still on server :D

**Comment by Tristiisch74** [comment]
Can you fix this ? Or can I have no unofficial version for fix this ?

**Comment by confuser** [comment]
Not tested, but please let me know if this is still an issue
