### ISSUE TITLE
[Question] BmAPI

### ISSUE THREAD

**Issue by ryans1230** [BanManagement/BanManager#680]
In developing a custom chat plugin on our bungee network, will I be able to check isMuted from the API (or anything else from the API for that matter)? Not sure if Ban Manager will load on the Bungee since it is mde for Spigot

**Comment by confuser** [comment]
BanManager does not run under Bungee. BmAPI will not be available in that context. It will only be usable in a Bukkit/Spigot context.

**Comment by feardevilz** [comment]
I feel there is a lot of potential to opening up the API to support both bukkit and bungee based drop ins. One of the major alternatives to this being Litebans which easily does just that and is a bit more superior than bm because of that. It lacks some of the functions and obviously open source repos.

@confuser Please reconsider adding bungee support for BM.

**Comment by confuser** [comment]
BM is designed to not be dependent on a particular proxy. What benefits would adding a Bungeecord plugin give other than checking for mutes? It has been quite some time since I worked with it, we had to switch to LilyPad on FC due to performance issues with Bungee, but that was a few years ago now. Is it not possible to check/cancel messages on the Spigot/Bukkit side?
