### ISSUE TITLE
Database connections going away

### ISSUE THREAD

**Issue by tkltw** [BanManagement/BanManager#681]
On plugin start the connection count according to MySQL's ```SHOW PROCESSLIST``` will match the amount of connections configured in the plugin config, over time the connection count starts to decrease to the point where there is only 1 left, this causes all kinds of issues such as players being stuck in the "Logging in" phase (indirectly causing issues with BungeeCord) and extremely slow BanManager commands. There do not appear to be any errors in the server log files.

**Comment by EvilOlaf** [comment]
Which BM version? How many connections did you configure?

**Comment by tkltw** [comment]
Latest from git, with minimum idle connections set to 0 and maximum pool size set to 10

**Comment by confuser** [comment]
Minimum idle connection should really be 1 at the very least

On 1 Oct 2016 19:24, "tkltw" <notifications@github.com> wrote:

Latest from git, with minimum idle connections set to 0 and maximum pool
size set to 10

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/BanManagement/BanManager/issues/681#issuecomment-250928434>,
or mute the thread

**Comment by tkltw** [comment]
With minimum idle enabled, I am experiencing the same issue, accompanied by "Connection is not available" exceptions. I only disabled minimum idle based on an issue over at HikariCP's repo suggesting that it's discouraged according to it's fixed pool design

**Comment by confuser** [comment]
Are you using any other mysql based plugins?

**Comment by tkltw** [comment]
I solved the issue by increasing the ```wait_timeout``` from MariaDB's Debian default of 600s to 8 hours with  ```maxLifeTime``` set to a minute less than that.
