### ISSUE TITLE
[how] Do I make all my bans from my survival also ban on my mini-games?

### ISSUE THREAD

**Issue by FrozenBeard** [BanManagement/BanManager#757]
I dont get the difference between local and global ban settings for the SQL.

I have always run banmanager on my survival, I have the local settings setup to that database on the same server, now I have recently made a second server on its own machine, which is firewalled to allow connections over port 3306 to the original database. So I just put in the same database details in the local setting on my games server to pull all bans from the survival? what happens if I ban from the survival? will it know they were banned from that server if I connect the database this way? if I do it this way I assume its one ban on one server, and banned on all servers?

**Comment by EvilOlaf** [comment]
`So I just put in the same database details in the local setting on my games server to pull all bans from the survival`
Yes.
`what happens if I ban from the survival?` 
The player will be banned and about 30 seconds later (depending on your sync settings) he won't be able to access the second server either.


The global setting is only needed if you want to explicitly ban a player from one certain server and not from the entire network....which basically does not happen often ^^

**Comment by FrozenBeard** [comment]
Ahhh gotcha! Just confused me the wording, Like Global and local are backwards, if you wanted bans per-server on the network then that would be a local ban, where as global is all servers on the network, just bad variable name conventions!
