### ISSUE TITLE
Implement Sponge BanService for compatibility with plugins.

### ISSUE THREAD

**Issue by clienthax** [BanManagement/BanManager#809]
https://docs.spongepowered.org/stable/en/plugin/bans.html

https://docs.spongepowered.org/stable/en/plugin/services.html

**Comment by confuser** [comment]
I've been doing some digging into this. It doesn't appear possible to overwrite the `BanService` with a custom implementation?

BanManager originally integrated with Bukkit/vanilla bans but was removed due to conflicts/compatibility issues when implementing UUID support quite some time ago. I'm hesitant about adding something similar back in again

**Comment by clienthax** [comment]
I don't see it being an issue with sponge, as it will redirect all calls to the service at the lowest level.

https://jd.spongepowered.org/7.1.0/org/spongepowered/api/service/ServiceManager.html
Seems to suggest that services are by definition replaceable

**Comment by clienthax** [comment]
@confuser it also seems that they are planning to remake the service, might be worth chiming in on https://github.com/SpongePowered/SpongeAPI/issues/1725
