### ISSUE TITLE
IPBan in /bmactivity

### ISSUE THREAD

**Issue by Nety01** [BanManagement/BanManager#871]
In /bmactivity show player name instead of his IP when the IP was banned and instead of [Ban] show type [IPBan]. 

Because I think that the IP doesn't really say anything to server admins, as they don't know who is it that way.

**Comment by confuser** [comment]
This is intentional. An ip ban is based on the ip address, not the player. The `/banip <playerName>` is simply a time saver to retrieve an ip address to ban by. That association is lost as soon as the player changes their ip address. Also consider that multiple players can have the same ip address, so showing the player name instead here would be odd, which one would be displayed?

**Comment by Nety01** [comment]
Umm well yeah, that's something I didn't think of...
